apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app-deployment
spec:
  replicas: 3 # Set the desired number of replicas
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: my-web-app
        image: akashm311/my-web-app:latest # Use the Docker image name
        ports:
        - containerPort: 5000 # Expose the port your application is listening on
