apiVersion: v1
kind: Service
metadata:
  name: my-web-app-service
spec:
  selector:
    app: my-web-app
  ports:
  - protocol: TCP
    port: 8083 # Port on which the service should listen
    targetPort: 5000 # Port on the container to forward traffic to
  type: NodePort # Expose the service externally using a NodePort
